Add upgrade variable
artis3n/ansible-role-tailscale pull request #113
Opened 2021-06-28 07:35 UTC by aleohl

Currently, the role checks for the presence of Tailscale. This change makes sure it upgrades to the latest version on run.

2021-06-28 13:50 UTC, artis3n commented
@aleohl Thanks for this PR! Can you elaborate on why the role should support updating the package? My initial thoughts are to keep that out of scope - an end user can run a package upgrade in the module for their package manager before or after the role runs if they would like to update this or other packages. The role always installs the latest at the moment if tailscale does not already exist on the machine, so we won't run into issues of trying to use config flags that don't exist in the current version.

2021-06-30 10:04 UTC, MiniCodeMonkey commented
I was just looking for a way to do this directly from the ansible role, this would be a nice addition!

2021-06-30 12:33 UTC, artis3n commented
All right, let's get it in then. Will add some comments to the PR

2021-06-30 12:37 UTC, artis3n requested changes
Please set the default to be `false` and take a look at my other comments.

2021-06-30 12:37 UTC, artis3n commented on defaults/main.yml
> +upgrade_release: true
This should be false by default for idempotency, people can elect for updates.

2021-06-30 12:37 UTC, artis3n commented on tasks/centos.yml
> +    state: present
`latest`

2021-06-30 12:37 UTC, artis3n commented on tasks/arch.yml
> +  when: not upgrade_release
Want to test this, pretty sure the `not` condition would still prefer `| bool`.

2021-07-01 04:20 UTC, aleohl commented
Sorry about the delay. I will make the required changes today (asap)

2021-07-04 16:56 UTC, artis3n commented
Thanks, @aleohl ! I will push up a PR forked from this to enable the CI tests to run, see https://github.com/artis3n/ansible-role-tailscale#development-and-contributing. Your commits and contribution to the repo will be preserved so you get credit.

2021-07-04 17:04 UTC, artis3n approved these changes

2021-07-04 17:20 UTC, artis3n commented
> 
> 
> @aleohl Thanks for this PR! Can you elaborate on why the role should support updating the package? My initial thoughts are to keep that out of scope - an end user can run a package upgrade in the module for their package manager before or after the role runs if they would like to update this or other packages. The role always installs the latest at the moment if tailscale does not already exist on the machine, so we won't run into issues of trying to use config flags that don't exist in the current version.

@aleohl @MiniCodeMonkey I've changed my mind on this. What do you think about setting the package to `latest` by default instead of `present`?

2021-07-10 19:30 UTC, artis3n commented
Merged in #116

2021-07-10 19:30 UTC, closed without merging

2021-07-16 06:44 UTC, aleohl commented
@artis3n happy to help out. Sorry about the lack of answers from me, been really busy.

2021-07-16 12:05 UTC, artis3n commented
@aleohl No worries! Thanks for this PR. The latest version of the role now uses `latest` by default.