Only refresh the apt cache if it is stale
artis3n/ansible-role-tailscale pull request #155
Opened 2021-11-23 06:38 UTC by kusold

This introduces a new role variable that allows people to set how long the apt-cache should remain valid for. Setting a high number allows for repeated use of this play without ansible reporting any changes.

If the age of the cache exceeds the configured value, the cache will be refreshed.

2021-11-23 14:13 UTC, artis3n requested changes
Thanks for this PR! Requesting some alternate refactoring in the comments.

Also, please add a `TAILSCALE_CI_KEY` to the secrets on your fork as documented in https://github.com/artis3n/ansible-role-tailscale#development-and-contributing so the CI suite can run.

2021-11-23 14:13 UTC, artis3n commented on defaults/main.yml
> +apt_cache_valid_time: 300 # 5 min
Let's move this to `vars/main.yml`. So end users can override if they want but should generally not be modified. That also means removing the reference from the README.

Also, why 5 minutes? Arbitrarily chosen or is that coming from a convention or best practice? Why not 10 minutes, or an hour?

2021-11-23 14:13 UTC, artis3n commented on tasks/debian.yml
> +  register: tailscale_apt_repo_result
Legacy Apt Dependencies is only called on older distros. Need to also register the task above it, Apt Dependencies, and include both in the conditional below.

And should the cache valid time be added to this apt task too?

2021-11-23 14:13 UTC, artis3n commented on README.md
> +### apt_cache_valid_time
As I explain in the other comment, remove from README.

2021-11-23 14:56 UTC, kusold commented on defaults/main.yml
> +apt_cache_valid_time: 300 # 5 min
It was arbitrarily chosen. For my personal use, I'll likely override this with a day. I chose the low time to keep it more similar to the existing behavior, but I can change it to anything.

2021-11-23 15:09 UTC, kusold commented on tasks/debian.yml
> +  register: tailscale_apt_repo_result
All the systems that use "Legacy Apt Dependencies" also use the normal "Apt Dependencies" so the cache will either be valid or updated there.

If the behavior changes so that it's either or, then we'll want to repeat it in that task.

2021-11-23 15:29 UTC, artis3n commented on tasks/debian.yml
> +  register: tailscale_apt_repo_result
According to https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html the default cache time is `0` so this may update the cache even with the tasks right next to each other. I guess it's a question of what actions you'd like to enforce in the role. As-is we don't need the force `true` on the update cache tasks which is an improvement for sure.

2021-11-23 15:33 UTC, artis3n commented on defaults/main.yml
> +apt_cache_valid_time: 300 # 5 min
Sounds good! In that case, let's arbitrarily bump to 1 hour (`3600`). From <https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html>: `As of Ansible 2.4, if explicitly set, this sets update_cache=yes.` So explicitly defining a short time will actually force the cache update more frequently than it would otherwise.

2022-01-28 19:04 UTC, artis3n commented
Based on this concern from above and me not being sure what impact that would have:

> Sounds good! In that case, let's arbitrarily bump to 1 hour (`3600`). From https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html: `As of Ansible 2.4, if explicitly set, this sets update_cache=yes.` So explicitly defining a short time will actually force the cache update more frequently than it would otherwise.

going to close this PR.

2022-01-28 19:04 UTC, closed without merging