Consider stailscale status returning 1 to be valid
artis3n/ansible-role-tailscale pull request #254
Opened 2022-11-03 08:52 UTC by toadjaune

# Problem

The current test with `tailscale status` is too restrictive, and fails the task in situations where we can bring the system back up and running with `tailscale up`

# Reproduction steps

* Initially setup a node with this role and an auth key
* wait for the auth key and the node authorization to expire (6 months, I think)
* re-execute the role *without* first rotating the auth key
* the role execution fails, at the `tailscale up` step (which is normal, since the auth key is invalid)
* facepalm for forgetting to rotate the auth key, then rotate the auth key
* the role execution still fails, at the `tailscale status` step

This is due to the fact that in this state, `tailscale status` returns 1, with the following message : 
```
# Health check:
#     - not logged in, last login error=invalid key: API key XXXXXXXXXXXX not valid

unexpected state: NoState
```

# Untested simpler reproduction steps

* Initially setup a node with this role, with an invalid auth key
* It fails
* Rotate the auth key and retry

# Proposed fix

This MR proposes a basic fix, adding tolerance of the tailscale CLI returning 1.
It was tested on my own infrastructure, and worked there (Debian 11 servers, role version 3.4.0, ansible version 2.12.10).

It is however probably not production-grade code, as it lacks :
* documentation of the situations this is useful in
* molecule tests

2022-11-04 00:10 UTC, artis3n commented
In previous iterations the tailscale status return code has been an issue - https://github.com/artis3n/ansible-role-tailscale/pull/97 . The assumptions made at that time may no longer be correct. It's worth taking another look at how this task is managing the `status` calls.

2022-11-06 17:31 UTC, artis3n requested changes
I wasn't aware this series of events triggered this error message - thank you for your clear and comprehensive set of reproduction steps!

I requested changed to continue providing strict checking on error status (exit code 1 will be a failure _except_ in certain conditions that we enumerate). Please also go through the Molecule tests, as most of the `verify.yml` files will need changes e.g. https://github.com/artis3n/ansible-role-tailscale/blob/main/molecule/default/verify.yml#L14

Once those edits occur and the existing tests pass, we'll get this merged!

2022-11-06 17:31 UTC, artis3n commented on tasks/install.yml
>      - "'Logged out.' not in tailscale_status.stdout"
Alternative to retain the granularity of the current check:
```suggestion
    - "'Logged out.' not in tailscale_status.stdout or 'not logged in' not in tailscale_status.stdout"
```

2022-11-06 17:31 UTC, artis3n commented on tasks/install.yml
>      or state_checksum != existing_state_checksum)
```suggestion
    and ('Logged out.' in tailscale_status.stdout
    or 'not logged in' in tailscale_status.stdout
    or state_checksum != existing_state_checksum)
```

2022-11-27 16:59 UTC, artis3n commented
Additionally - please merge the latest changes from main, as that will resolve the failing Debian 12 check.

2023-01-01 19:51 UTC, artis3n commented
Completed in #280

2023-01-01 19:51 UTC, closed without merging

2023-01-05 18:10 UTC, toadjaune commented
Thanks a lot for that :)