[FEAT] Improve tags support
artis3n/ansible-role-tailscale pull request #407
Opened 2023-12-23 14:42 UTC by McSim85

🎄  🎅 🌲   Merry Christmas PR that fixes https://github.com/artis3n/ansible-role-tailscale/issues/406

2023-12-24 03:32 UTC, artis3n requested changes
Thank you for this PR! Some documentation and code changes requested, and some debugging needed on the `tag:` prepend. You can test locally by following [these instructions](https://github.com/artis3n/ansible-role-tailscale#development-and-contributing) and running the various `make` commands in the Makefile. I recommend `make test-default` for the "default" molecule scenario, and `make test-oauth` for the oauth test.

2023-12-24 03:32 UTC, artis3n commented on README.md
> +Tags are required for OAuth clients managing devices (`tailscale_authkey` OAuth key).
A rewrite, and adding information on how users should format input:

```suggestion
Apply supplied tags to the Tailscale nodes configured by this role (via the `--advertise-tags` flag to `tailscale up`).
For more information, see [What are tags?](https://tailscale.com/kb/1068/acl-tags?q=acl%20tag#what-are-acl-tags)

> [!NOTE]
> Tags are required for OAuth clients (`tailscale_authkey` OAuth key).

Entries should not include `tag:`.
For example, `tailscale_args: ['worker']` translates to `--advertise-tags=tag:worker`.
```

2023-12-24 03:32 UTC, artis3n commented on README.md
> +> Use the `tailscale_tags` variable instead.
We can replace this entirely with:

```markdown
> **Do not use this for `--advertise-tags`.**
> Use the `tailscale_tags` variable instead.
```

2023-12-24 03:32 UTC, artis3n commented on defaults/main.yml
> +tailscale_timeout: "120s"
To specify, as there may be other timeouts:

```suggestion
tailscale_up_timeout: "120s"
```

2023-12-24 03:32 UTC, artis3n commented on defaults/main.yml
> +# Required device tags to advertise
```suggestion
# Apply provided tags to node
```

2023-12-24 03:32 UTC, artis3n commented on tasks/install.yml
> +    tailscale_tags: "{{ tailscale_tags | map('regex_replace', '^', 'tag:') | list }}"
Would rather save a new fact and leave the user-provided variable intact.

```suggestion
    tailscale_prepared_tags: "{{ tailscale_tags | map('regex_replace', '^', 'tag:') | list }}"
```

2023-12-24 03:32 UTC, artis3n commented on tasks/install.yml
> +    tailscale_args: "{{ tailscale_args }} {{ tailscale_tags_string | trim }} --timeout={{ tailscale_timeout | trim }}"
Don't overwrite the user input variable, create a new variable if needed

2023-12-24 03:32 UTC, artis3n commented on tasks/install.yml
> +      --advertise-tags={{ tailscale_tags | join(',') }}
```suggestion
      --advertise-tags={{ tailscale_prepared_tags | join(',') }}
```

2023-12-24 03:32 UTC, artis3n commented on tasks/main.yml
> +    msg: "When `tailscale_authkey` is OAuth key, you must set tags `tailscale_tags`."
```suggestion
    msg: "When `tailscale_authkey` is an OAuth key, you must supply one or more tags in `tailscale_tags`."
```

2023-12-24 03:32 UTC, artis3n commented on tasks/main.yml
> +    msg: You can use tailscale_tags, instead of tailscale_args to assign tags.
```suggestion
    msg: You must use `tailscale_tags` instead of `tailscale_args` to assign tags.
```

2023-12-24 03:32 UTC, artis3n commented on tasks/main.yml
> +- name: Use tailscale_tags instead of tailscale_args for tags
Nice validation check!

2023-12-24 03:32 UTC, artis3n commented on tasks/install.yml
> +    tailscale_args: "{{ tailscale_args }} {{ tailscale_tags_string | trim }} --timeout={{ tailscale_timeout | trim }}"
```suggestion
    tailscale_args: "{{ tailscale_args }} {{ tailscale_tags_string | trim }} --timeout={{ tailscale_up_timeout | trim }}"
```

2023-12-24 03:32 UTC, artis3n commented on tasks/install.yml
> +    tailscale_args: "{{ tailscale_args }} {{ tailscale_tags_string | trim }} --timeout={{ tailscale_timeout | trim }}"
Since we are binding `--timeout`, that needs to be added to the list of flags that are not acceptable to input into `tailscale_args` on the README.

2023-12-24 03:32 UTC, artis3n commented on tasks/install.yml
> +    tailscale_tags: "{{ tailscale_tags | map('regex_replace', '^', 'tag:') | list }}"
Debug this locally, it does not appear to be prepending `tag:`
![image](https://github.com/artis3n/ansible-role-tailscale/assets/6969296/2caa60cc-1a41-4e6d-bd00-307c507b2975)

2023-12-24 19:30 UTC, McSim85 commented
> Thank you for this PR! Some documentation and code changes requested, and some debugging needed on the `tag:` prepend. You can test locally by following [these instructions](https://github.com/artis3n/ansible-role-tailscale#development-and-contributing) and running the various `make` commands in the Makefile. I recommend `make test-default` for the "default" molecule scenario, and `make test-oauth` for the oauth test.

I appreciate detailed reviewing and comments.
Unfortunately, the current environment is incompatible with MacOS because of docker (I think). I am getting the exception:
```python
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
make: *** [test-default] Error 1
```  
But I added debug tasks and tested the installation on a real machine:
```yaml
TASK [ansible-role-tailscale : Install | Tailscale version and online status] ****************************************************************
ok: [servername] =>
  msg: 'Ver: 1.56.1-t906f85d10-g34ed54c8c Online: False'

TASK [ansible-role-tailscale : Install | Prepend 'tag:' to each item in the list] ************************************************************
ok: [servername] => changed=false
  ansible_facts:
    tailscale_prepared_tags:
    - tag:testnode
    - tag:devenv
    - tag:ci-worker

TASK [ansible-role-tailscale : Install | Build `tailscale up` arguments strings] *************************************************************
ok: [servername] => changed=false
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'

TASK [ansible-role-tailscale : Install | Authkey Type] ***************************************************************************************
ok: [servername] =>
  msg: OAuth Client Secret

TASK [ansible-role-tailscale : Install | Build the final tailscale_args] *********************************************************************
ok: [servername] => changed=false
  ansible_facts:
    tailscale_args_string: ' --advertise-tags=tag:testnode,tag:devenv,tag:ci-worker --timeout=120s'

TASK [ansible-role-tailscale : Install | Final `tailscale up` arguments string] **************************************************************
ok: [servername] =>
  msg: --advertise-tags=tag:testnode,tag:devenv,tag:ci-worker --timeout=120s

```

2023-12-24 19:37 UTC, McSim85 commented
I will set up a Linux environment for molecule, but later.
Please let me know if you see any issues with the current PR. 🙏

2023-12-25 19:23 UTC, artis3n approved these changes
Nice work! Thanks for these contributions

2023-12-25 19:23 UTC, merged