feat: added Linux Mint Support
artis3n/ansible-role-tailscale pull request #515
Opened 2024-11-16 14:34 UTC by fkonradmain

Added Linux Mint support.

Following Problems induced changes:

1. the codename for `name: Debian | Add Tailscale Deb` would point to `wilma` but it should be `noble` (`viriginia` -> `jammy`, etc. respectively)
   Solution:
     - introduction of a mapping dict `tailscale_debian_release`, that replaces sub distro codenames to parent distro code names.
     - added Value for `codename` when calling `ansible.builtin.apt_repository`, but only if the codename has to be overridden

2. Linux Mint was not among the list of supported operating systems
   Solution: added entries for Linux Mint at `tailscale_debian_family_distros`
  

3. URLs would include `linux mint` or `wilma` instead of `ubuntu` and `noble` (e.g. `https://pkgs.tailscale.com/stable/linux mint/wilma.noarmor.gpg` instead of `https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg`)
   Solution:
     - also added entries for Linux mint at `tailscale_debian_distro`
     - added functionality to actually look up table values from `tailscale_debian_distro` with automatic fallback to `ansible_distribution`

Currently supported:
- Linux Mint 22

Tested on:
- Linux Mint 22
- Debian 12

Closes #516

2024-11-16 16:02 UTC, artis3n requested changes
Thank you for submitting this PR!

In order to add a new supported distro, the following additional steps need to be added:

1. Update Galaxy metadata (https://github.com/artis3n/ansible-role-tailscale/blob/main/meta/main.yml#L11)
2. Build a testable Molecule container for the distro (e.g. https://github.com/geerlingguy/docker-ubuntu2404-ansible and https://github.com/artis3n/docker-rhel9-ansible)
3. Ensure the test suite runs successfully on the container (https://github.com/artis3n/ansible-role-tailscale/blob/main/Makefile#L32) (`MOLECULE_DISTRO=your-distro-here make test-all`)
4. Add the container to the CI suite (https://github.com/artis3n/ansible-role-tailscale/blob/main/.github/workflows/pull_request_target.yml#L26)

2024-11-16 20:01 UTC, fkonradmain commented on vars/main.yml
> +  wilma: noble
Resolved this by automatically retrieving `UBUNTU_CODENAME` on Ubuntu based distros, while still using `ansible_distribution_release` on debian based distros.

2024-11-16 21:08 UTC, artis3n commented
Ah, TIL `platforms` isn't respected by Galaxy anymore anyway
https://forum.ansible.com/t/role-meta-data-platform-key-broken/4651/9

2024-11-16 21:13 UTC, artis3n commented
Looks like `apt_codename` needs to be handled in the uninstall tasks: https://github.com/artis3n/ansible-role-tailscale/actions/runs/11873194056/job/33087762830?pr=515#step:6:277

2024-11-16 21:17 UTC, fkonradmain commented
> Looks like `apt_codename` needs to be handled in the uninstall tasks: https://github.com/artis3n/ansible-role-tailscale/actions/runs/11873194056/job/33087762830?pr=515#step:6:277

I will take care of that.

2024-11-16 21:50 UTC, fkonradmain commented on .github/workflows/pull_request_target.yml
> +          - image: ghcr.io/fkonradmain/docker-linuxmint22-ansible:latest
@artis3n I don't see this pop up in the test suite. Does this need additional approval from your side as owner or did I miss anything?

2024-11-16 22:49 UTC, artis3n commented
Why is this image 4+GB? The other ubuntu-based ones are much smaller 🤔

2024-11-16 22:50 UTC, artis3n commented on .github/workflows/pull_request_target.yml
> +          - image: ghcr.io/fkonradmain/docker-linuxmint22-ansible:latest
`pull_request_target` works by running the version of this file on the _main_ branch against the code we check out. Needed to safely use my tailscale key to run the CI. Side effect is any changes to this file won't reflect in tests until it is merged.

To test this container, I run `MOLECULE_DISTRO="ghcr.io/fkonradmain/docker-linuxmint22-ansible:latest" make test` locally (or the other test commands in the Makefile)

2024-11-16 22:54 UTC, artis3n commented on tasks/debian/common.yml
> +- name: Debian | Apt Dependencies
Why include this here? There is also the legacy apt dependency task.

Perhaps call this file `tasks/debian/distro_codename.yml` and just include the first 3 tasks.

2024-11-16 22:54 UTC, artis3n commented on tasks/debian/install.yml
> +- name: Debian | Include common dependencies for install and uninstall
If you make the changes in `common.yml`, then rename this task

2024-11-16 22:54 UTC, artis3n commented on tasks/debian/uninstall.yml
> -    state: present
🤔 I am not sure why I'm installing apt dependencies in the uninstall task to begin with. Need to look into that.

2024-11-17 18:39 UTC, artis3n approved these changes
Thanks for making these changes!

2024-11-17 18:39 UTC, artis3n commented on tasks/debian/apt-codename.yml
> +# | Linux Mint       | "ubuntu debian"        |
Great comment block, thank you!

2024-11-17 18:39 UTC, artis3n commented on tasks/debian/apt-codename.yml
> +# This value points to the actual ubuntu Version t
Small typo at the end of this!

2024-12-03 17:36 UTC, artis3n commented on tasks/debian/apt-codename.yml
> +# This value points to the actual ubuntu Version t
@fkonradmain if you could just adjust this comment!

2024-12-03 17:49 UTC, artis3n approved these changes

2024-12-04 02:10 UTC, artis3n commented on tasks/debian/apt-codename.yml
> +# This value points to the actual ubuntu Version t
Yeah something changed in the rockylinux distros, I don't think it is related to this PR. I need to go investigate it.

2024-12-13 15:48 UTC, merged